name: tickets-api

services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - laravel-storage-production:/var/www/storage
    networks:
      - laravel-production
    depends_on:
      api:
        condition: service_started

  api:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      target: production
    image: tickets-api:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - laravel-storage-production:/var/www/storage
    networks:
      - laravel-production
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine3.23
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - laravel-db-data:/var/lib/postgresql/data
    networks:
      - laravel-production
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - laravel-production
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  typesense:
    image: typesense/typesense:30.1
    restart: unless-stopped
    ports:
      - 8108:8108
    volumes:
      - typesense-data:/data
    command: >
      --data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors
    networks:
      - laravel-production

networks:
  laravel-production:


volumes:
  laravel-db-data:
  laravel-storage-production:
  typesense-data:
